version: '3.3'
services:
  web:
    image: api:latest
    container_name: hapivuemongo
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
#DB
  mongo:
    image: mongo:latest
    container_name: mongod
    restart: always
    ports:
      - 27017:27017    
  mongodb_feed:
    image: mongo:latest
    container_name: mongodb_feed
    command: mongoimport --host 127.0.0.1 --port 27018 -d CID -c reports --type csv --file ./crime_incident_dump.csv --headerline
    volumes: 
      - ./crime_incident_dump.csv
    ports:
      - 27018:27018
      
  # mongoimport --host mongo --port 27018 --db test --mode upsert --type csv --file ./crime_incident_dump.csv
    