####################################################################################################
# Creating container PHP
####################################################################################################
phpmongo:
    build: ./image/phpmongo/
    ports:
        - "9002:9000"
    volumes:
        - ./microservice/lumen-mongo/www/lumen/:/var/www/html
    
####################################################################################################
# Creating container PHP
####################################################################################################
phpmysqlcsv:
    build: ./image/php/
    ports:
        - "9000:9000"
    volumes:
        - ./microservice/exportCsv/www/lumen/:/var/www/html
####################################################################################################
# Creating container (Nginx)
####################################################################################################
nginxcsv:
    image: nginx:latest
    ports:
        - "8000:80"
    volumes:
        - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - phpmysqlcsv:php
####################################################################################################
# Creating container PHP
####################################################################################################
phpcreateuser:
    build: ./image/php/
    ports:
        - "9001:9000"
    volumes:
        - ./microservice/createUser/www/lumen/:/var/www/html
####################################################################################################
# Creating container (Nginx)
####################################################################################################
nginxuser:
    image: nginx:latest
    ports:
        - "8001:80"
    volumes:
        - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - phpcreateuser:php

nginxmongo:
    image: nginx:latest
    ports:
        - "8002:80"
    volumes:
        - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - phpmongo:php

web:
  build: ./image/hapi
  ports:
    - 80:80
#DB
mongo:
  image: mongo:latest
  restart: always
  ports:
    - 27017:27017    
mongodb_feed:
  image: mongo:latest
  command: mongoimport --host 192.168.110.133 --type csv --collection HapiVueMongo --db CID --headerline --file '/home/crime_incident_dump.csv'
  volumes: 
    - ./src/crime_incident_reports.datadump-2.csv:/home/crime_incident_dump.csv
  ports:
    - 27018:27018
mysql:
  build: ./image/mymysql/
  restart: always
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: example
