version: '3.3'
services:
  web:
    image: api:latest
    container_name: hapivuemongo
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
#DB
  mongo:
    image: mongo:latest
    container_name: mongod
    restart: always
    ports:
      - 27017:27017    
  mongodb_feed:
    image: mongo:latest
    container_name: mongodb_feed
    command: mongoimport --host mongod --type csv --collection HapiVueMongo --db CID --headerline --file '/home/crime_incident_dump.csv'
    volumes: 
      - ./src/crime_incident_dump.csv:/home/crime_incident_dump.csv
    ports:
      - 27018:27018
  db:
    build: ./image/mymysql
    restart: always
    ports:
      - 3306:3306
    container_name: mysql_authentication
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=alex
      - MYSQL_PASSWORD=test

